DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS systems;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS system_devices;
DROP TABLE IF EXISTS compare;
DROP TABLE IF EXISTS kpi;